export const GET_PRODUCT_T_SHIRT_REQUEST = 'GET_PRODUCT_T_SHIRT_REQUEST';
export const GET_PRODUCT_T_SHIRT_SUCCESS = 'GET_PRODUCT_T_SHIRT_SUCCESS';
export const GET_PRODUCT_T_SHIRT_ERROR = 'GET_PRODUCT_T_SHIRT_ERROR';

export const GET_PRODUCT_KIDS_REQUEST = 'GET_PRODUCT_KIDS_REQUEST';
export const GET_PRODUCT_KIDS_SUCCESS = 'GET_PRODUCT_KIDS_SUCCESS';
export const GET_PRODUCT_KIDS_ERROR = 'GET_PRODUCT_KIDS_ERROR';
