export const GET_ALL_CUSTOMERS_BY_ADMIN_REQUEST =
  'GET_ALL_CUSTOMER_BY_ADMIN_REQUEST';
export const GET_ALL_CUSTOMERS_BY_ADMIN_SUCCESS =
  'GET_ALL_CUSTOMER_BY_ADMIN_SUCCESS';
export const GET_ALL_CUSTOMERS_BY_ADMIN_ERROR =
  'GET_ALL_CUSTOMER_BY_ADMIN_ERROR';
