export const GET_ALL_USERS_BY_ADMIN_REQUEST = 'GET_ALL_USERS_BY_ADMIN_REQUEST';
export const GET_ALL_USERS_BY_ADMIN_SUCCESS = 'GET_ALL_USERS_BY_ADMIN_SUCCESS';
export const GET_ALL_USERS_BY_ADMIN_ERROR = 'GET_ALL_USERS_BY_ADMIN_ERROR';

export const GET_USER_BY_ADMIN_REQUEST = 'GET_USER_BY_ADMIN_REQUEST';
export const GET_USER_BY_ADMIN_SUCCESS = 'GET_USER_BY_ADMIN_SUCCESS';
export const GET_USER_BY_ADMIN_ERROR = 'GET_USER_BY_ADMIN_ERROR';

export const UPDATE_USER_BY_ADMIN_REQUEST = 'UPDATE_USER_BY_ADMIN_REQUEST';
export const UPDATE_USER_BY_ADMIN_SUCCESS = 'UPDATE_USER_BY_ADMIN_SUCCESS';
export const UPDATE_USER_BY_ADMIN_ERROR = 'UPDATE_USER_BY_ADMIN_ERROR';

export const GET_EMPLOYEE_ORDER_BY_ADMIN_REQUEST =
  'GET_EMPLOYEE_ORDER_BY_ADMIN_REQUEST';
export const GET_EMPLOYEE_ORDER_BY_ADMIN_SUCCESS =
  'GET_EMPLOYEE_ORDER_BY_ADMIN_SUCCESS';
export const GET_EMPLOYEE_ORDER_BY_ADMIN_ERROR =
  'GET_EMPLOYEE_ORDER_BY_ADMIN_ERROR';
