export const GET_REVIEW_BY_PRODUCT_REQUEST = 'GET_REVIEW_BY_PRODUCT_REQUEST';
export const GET_REVIEW_BY_PRODUCT_SUCCESS = 'GET_REVIEW_BY_PRODUCT_SUCCESS';
export const GET_REVIEW_BY_PRODUCT_ERROR = 'GET_REVIEW_BY_PRODUCT_ERROR';

export const GET_PRODUCT_INVOLVE_REQUEST = 'GET_PRODUCT_INVOLVE_REQUEST';
export const GET_PRODUCT_INVOLVE_SUCCESS = 'GET_PRODUCT_INVOLVE_SUCCESS';
export const GET_PRODUCT_INVOLVE_ERROR = 'GET_PRODUCT_INVOLVE_ERROR';

export const ADD_REVIEW_BY_PRODUCT_REQUEST = 'ADD_REVIEW_BY_PRODUCT_REQUEST';
export const ADD_REVIEW_BY_PRODUCT_SUCCESS = 'ADD_REVIEW_BY_PRODUCT_SUCCESS';
export const ADD_REVIEW_BY_PRODUCT_ERROR = 'ADD_REVIEW_BY_PRODUCT_ERROR';

export const GET_RATE_BY_PRODUCT_REQUEST = 'GET_RATE_BY_PRODUCT_REQUEST';
export const GET_RATE_BY_PRODUCT_SUCCESS = 'GET_RATE_BY_PRODUCT_SUCCESS';
export const GET_RATE_BY_PRODUCT_ERROR = 'GET_RATE_BY_PRODUCT_ERROR';

export const ADD_RATE_BY_PRODUCT_REQUEST = 'ADD_RATE_BY_PRODUCT_REQUEST';
export const ADD_RATE_BY_PRODUCT_SUCCESS = 'ADD_RATE_BY_PRODUCT_SUCCESS';
export const ADD_RATE_BY_PRODUCT_ERROR = 'ADD_RATE_BY_PRODUCT_ERROR';

export const GET_IMAGES_BY_PRODUCT_REQUEST = 'GET_IMAGES_BY_PRODUCT_REQUEST';
export const GET_IMAGES_BY_PRODUCT_SUCCESS = 'GET_IMAGES_BY_PRODUCT_SUCCESS';
export const GET_IMAGES_BY_PRODUCT_ERROR = 'GET_IMAGES_BY_PRODUCT_ERROR';
