export const GET_API_CITIES_REQUEST = 'GET_API_CITIES_REQUEST';
export const GET_API_CITIES_SUCCESS = 'GET_API_CITIES_SUCCESS';
export const GET_API_CITIES_ERROR = 'GET_API_CITIES_ERROR';

export const GET_API_DISTRICTS_REQUEST = 'GET_API_DISTRICTS_REQUEST';
export const GET_API_DISTRICTS_SUCCESS = 'GET_API_DISTRICTS_SUCCESS';
export const GET_API_DISTRICTS_ERROR = 'GET_API_DISTRICTS_ERROR';

export const GET_API_WARDS_REQUEST = 'GET_API_WARDS_REQUEST';
export const GET_API_WARDS_SUCCESS = 'GET_API_WARDS_SUCCESS';
export const GET_API_WARDS_ERROR = 'GET_API_WARDS_ERROR';

export const CHECK_OUT_ORDER_REQUEST = 'CHECK_OUT_ORDER_REQUEST';
export const CHECK_OUT_ORDER_SUCCESS = 'CHECK_OUT_ORDER_SUCCESS';
export const CHECK_OUT_ORDER_ERRROR = 'CHECK_OUT_ORDER_ERRROR';
