// export const GET_ALL_CATEGORY_BY_ADMIN_REQUEST =
//   'GET_ALL_CATEGORY_BY_ADMIN_REQUEST';
// export const GET_ALL_CATEGORY_BY_ADMIN_SUCCESS =
//   'GET_ALL_CATEGORY_BY_ADMIN_SUCCESS';
// export const GET_ALL_CATEGORY_BY_ADMIN_ERROR =
//   'GET_ALL_CATEGORY_BY_ADMIN_ERROR';

// // get all color by admin
// export const GET_ALL_COLOR_BY_ADMIN_REQUEST = 'GET_ALL_COLOR_BY_ADMIN_REQUEST';
// export const GET_ALL_COLOR_BY_ADMIN_SUCCESS = 'GET_ALL_COLOR_BY_ADMIN_SUCCESS';
// export const GET_ALL_COLOR_BY_ADMIN_ERROR = 'GET_ALL_CATEGORY_BY_ADMIN_ERROR';

// export const GET_ALL_SIZE_BY_ADMIN_REQUEST = 'GET_ALL_SIZE_BY_ADMIN_REQUEST';
// export const GET_ALL_SIZE_BY_ADMIN_SUCCESS = 'GET_ALL_SIZE_BY_ADMIN_SUCCESS';
// export const GET_ALL_SIZE_BY_ADMIN_ERROR = 'GET_ALL_SIZE_BY_ADMIN_ERROR';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';
