export const GET_ORDERS_BY_CUSTOMER_REQUEST = 'GET_ORDERS_BY_CUSTOMER_REQUEST';
export const GET_ORDERS_BY_CUSTOMER_SUCCESS = 'GET_ORDERS_BY_CUSTOMER_SUCCESS';
export const GET_ORDERS_BY_CUSTOMER_ERROR = 'GET_ORDERS_BY_CUSTOMER_ERROR';

export const GET_ORDER_BY_CUSTOMER_REQUEST = 'GET_ORDER_BY_CUSTOMER_REQUEST';
export const GET_ORDER_BY_CUSTOMER_SUCCESS = 'GET_ORDER_BY_CUSTOMER_SUCCESS';
export const GET_ORDER_BY_CUSTOMER_ERROR = 'GET_ORDER_BY_CUSTOMER_ERROR';
