export const UPLOAD_IMAGE_BY_PROFILE_REQUEST =
  'UPLOAD_IMAGE_BY_PROFILE_REQUEST';
export const UPLOAD_IMAGE_BY_PROFILE_SUCCESS =
  'UPLOAD_IMAGE_BY_PROFILE_SUCCESS';
export const UPLOAD_IMAGE_BY_PROFILE_ERROR = 'UPLOAD_IMAGE_BY_PROFILE_ERROR';
