export const UPDATE_PROFILE_BY_CUSTOMER_REQUEST =
  'UPDATE_PROFILE_BY_CUSTOMER_REQUEST';
export const UPDATE_PROFILE_BY_CUSTOMER_SUCCESS =
  'UPDATE_PROFILE_BY_CUSTOMER_SUCCESS';
export const UPDATE_PROFILE_BY_CUSTOMER_ERROR =
  'UPDATE_PROFILE_BY_CUSTOMER_ERROR';
